FROM gobuffalo/buffalo:development

RUN apt-get update && apt-get upgrade -y

EXPOSE 3000

RUN mkdir -p $GOPATH/src/github.com/daylightdata/shortbread
COPY . $GOPATH/src/github.com/daylightdata/shortbread
WORKDIR $GOPATH/src/github.com/daylightdata/shortbread

ENV ADDR 0.0.0.0
ENV GO_ENV development
