version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/go/src/github.com/daylightdata/shortbread
    command: [ "sh", "-c", "buffalo db migrate ; exec buffalo dev" ]
    env_file: .env
  postgres:
    image: postgres:9
    ports:
      - "5432:5432"
